name: mboston
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  bloc: ^8.1.4
  get_it: ^7.7.0
  go_router: ^14.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
